name: test suite
on: [push, pull_request]

jobs:
  test:
    name: nargo test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install noirup
        run: |
          curl -L https://raw.githubusercontent.com/noir-lang/noirup/refs/heads/main/install | bash
          echo "$HOME/.nargo/bin" >> $GITHUB_PATH
      - name: Install Noir and run tests
        run: |
          noirup -v 1.0.0-beta.6
          nargo test
