name: test suite
on: [push, pull_request]

jobs:
  test:
    name: nargo test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          curl -L https://raw.githubusercontent.com/noir-lang/noirup/refs/heads/main/install | bash
          noirup -v 1.0.0-beta.6
          nargo test
